---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: truck-APP_NAME
  #namespace: logistic
  labels:
    app: truck-APP_NAME
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: truck-APP_NAME
  template:
    metadata:
      labels:
        app: truck-APP_NAME
        date: "_DATE_"
    spec:
      #imagePullSecrets:
      #- name: regcred
      terminationGracePeriodSeconds: 180
      restartPolicy: Always
      containers:
      - name: truck-APP_NAME
        image: asia.gcr.io/ghn-logistic/logistic_phoenix:_VERSION_
        ports:
        - containerPort: 9090
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: env-env
        env:
        - name: DATABASE__HOST
          value: 10.148.0.2
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "60Mi"
            cpu: "70m"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: truck-APP_NAME
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: truck-APP_NAME
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: truck-APP_NAME
  #namespace: station
spec:
  selector:
    app: truck-APP_NAME
  type: NodePort # Test kong ingress
  ports:
  ####### Kong Ingress
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: truck-APP_NAME
---